name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: major
template: |
  $TITLE

  ## CHANGES

  $CHANGES

  ## CONTRIBUTORS

  $CONTRIBUTORS

  ## PREVIOUS_TAG
  
  $PREVIOUS_TAG

  ## REPOSITORY
  
  $REPOSITORY

  ## OWNER
  
  $OWNER
autolabeler:
  - label: 'chore'
    files:
      - '*.js", "*.css", "*.html", "*.vue'
  - label: 'bug'
    files:
      - '*.js", "*.css", "*.html", "*.vue'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    files:
      - '*.js", "*.css", "*.html", "*.vue'
    body:
      - '/JIRA-[0-9]{1,4}/'