name: build and deploy after release is published

on: 
  release:
    types: [published]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered build and deployment
        run: |
          echo "release version ${{ github.ref_name }}"
