name: Bump version and push tag

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      bumb:
        description: "bumb"
        required: false
        default: "prerelease"
        type: choice
        options:
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
          - prerelease
      preId:
        description: "default value to differnt for workflow trigger and pull request trigger. select only this i the bumb is pre"
        required: false
        type: choice
        options:
          -
          - premajor
          - preminor
          - prepatch
          - prerelease
      releaseType:
        description: "Select the release type. By default only tag will be created. if you want to create a release with the tag select the type. se;ect release for [preid is empty]"
        type: choice
        required: false
        options:
          -
          - draft
          - publish
    
# permissions:
#   contents: write

jobs:
  createTag:
    name: "Create tag"
    if:  github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' 
    runs-on: ubuntu-latest
    steps:
      - name: Get bumb value
        uses: haya14busa/action-cond@v1
        id: getBumb
        with:
          cond: ${{ github.event_name == 'workflow_dispatch'}}
          if_true: ${{ inputs.bumb }}
          if_false: 'prerelease'

      - name: Get bumb value, if provided
        uses: haya14busa/action-cond@v1
        id: getPreId
        with:
          cond: ${{ github.event_name == 'workflow_dispatch'}}
          if_true: ${{ inputs.preId }}
          if_false: 'prerelease'
      - run: |
          echo "bumb: ${{ steps.getBumb.outputs.value }}"
          echo "prefix: ${{ steps.getPreId.outputs.value }}"
  
      - id: createNextTag
        name: "Create tag"
        uses: zwaldowski/semver-release-action@v3
        with: 
          prefix: "v"
          preid: ${{ steps.getPreId.outputs.value }}       
          bump:  ${{ steps.getBumb.outputs.value }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Tag ${{ steps.createNextTag.outputs.version_tag }} created!"
    outputs:
      newTag: ${{ steps.createNextTag.outputs.version_tag }}


  createRelease:
    name: "Create release"
    if: github.event_name == 'workflow_dispatch' && (inputs.releaseType == 'publish' || inputs.releaseType == 'draft')
    runs-on: ubuntu-latest
    needs: createTag
    steps:
      - name: Create release
        id: createNewRelease
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: ${{ needs.createTag.outputs.newTag }}
          create_draft: ${{ inputs.releaseType == 'draft' }}
          release_title:  Release ${{ needs.createTag.outputs.newTag }}
          changelog_file: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "created release ${{ needs.createTag.outputs.newTag }} ${{ steps.createNewRelease.outputs.html_url }}!"
