name: Create TAG Julia TagBot

on:
  workflow_dispatch:
    # inputs:
    #   releaseTag:
    #     description: "Release Tag"
    #     required: true
    #     default: "null"
    #     type: string
    
permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: "v0.1.0"
          message: "creating v1.0.0.1452"
          token: ${{ secrets.GITHUB_TOKEN }}