name: Create TAG Julia TagBot

on:
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
jobs:
  TagBot:
    - name: bump-everywhere
    uses: undergroundwires/bump-everywhere@1.4.0
