name: Bump version and push tag

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      bumb:
        description: "bumb"
        required: false
        default: "prerelease"
        type: choice
        options:
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
          - prerelease
      preId:
        description: "default value to differnt for workflow trigger and pull request trigger"
        required: false
        type: choice
        options:
          -
          - premajor
          - preminor
          - prepatch
          - prerelease
      releaseType:
        description: "Select the release type. By default only tag will be created. if you want to create a release with the tag select the type."
        type: choice
        required: false
        options:
          -
          - draft
          - publish
    
# permissions:
#   contents: write

jobs:
# todo: ann check env and create can be merged
  env:
    name: "create Parameters no need of camel case"
    runs-on: ubuntu-latest
    steps:
      - name: set bumb value
        uses: haya14busa/action-cond@v1
        id: setBumb
        with:
          cond: ${{ github.event_name == 'workflow_dispatch'}}
          if_true: ${{ inputs.bumb }}
          if_false: 'prerelease'

      - name: Check preId from workflow dispatch input
        uses: haya14busa/action-cond@v1
        id: setPreId
        with:
          cond: ${{ github.event_name == 'workflow_dispatch'}}
          if_true: ${{ inputs.preId }}
          if_false: 'prerelease'
      - run: |
          echo "${{ steps.setPreId.outputs.value }}"
          echo "${{ steps.setBumb.outputs.value }}"
    outputs:
      calculatedBumb: ${{ steps.setBumb.outputs.value }}
      calculatedPreId: ${{ steps.setPreId.outputs.value }}


  createTag:
    name: "createTag"
    runs-on: ubuntu-latest
    needs:
      - env
    steps:
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with: 
          prefix: "v"
          preid: ${{ needs.env.outputs.calculatedPreId }}        
          bump: ${{ needs.env.outputs.calculatedBumb }}
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # todo: ann check this output
      - run: |
          echo "${{ steps.next_version.outputs.version }}"
          echo "${{ steps.next_version.outputs.version_tag }}"
    outputs:
      newTag: ${{ steps.next_version.outputs.version_tag }}


  createRelease:
    name: "createRelease"
    if: github.event_name == 'workflow_dispatch' && (inputs.releaseType == 'publish' || inputs.releaseType == 'draft')
    runs-on: ubuntu-latest
    needs: [env , createTag]
    steps:
      # - uses: actions/checkout@v3
      - name: Upload release notes
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: ${{ needs.createTag.outputs.newTag }}
          create_draft: ${{ inputs.releaseType == 'draft' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
