name: Create TAG Julia TagBot

on:
  workflow_dispatch:
    # inputs:
    #   releaseTag:
    #     description: "Release Tag"
    #     required: true
    #     default: "null"
    #     type: string
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ env.github-token }}
          tag: ${{ steps.package-version.outputs.version }}