name: Bump version and push tag

on:
  workflow_dispatch:
    # inputs:
    #   releaseTag:
    #     description: "Release Tag"
    #     required: true
    #     default: "null"
    #     type: string
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with: 
          prefix: "v"
          preid: prerelease        
          bump: prerelease
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
