name: Bump version and push tag

on:
  workflow_dispatch:
    # inputs:
    #   releaseTag:
    #     description: "Release Tag"
    #     required: true
    #     default: "null"
    #     type: string
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with:            
          bump: prepatch
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
      # - uses: zwaldowski/semver-release-action@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     sha: ${{ steps.git_commit.outputs.sha }}