name: Bump version and push tag

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      bumb:
        description: "bumb"
        required: false
        default: "prerelease"
        type: string
      preId:
        description: "preId"
        required: false
        default: "prerelease"
        type: string
    
# permissions:
#   contents: write

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - name: set bumb value
        uses: haya14busa/action-cond@v1
        id: setBumb
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' && inputs.bumb != 'prerelease' }}
          if_true: ${{ inputs.bumb }}
          if_false: 'prerelease'

      - name: Check preId from workflow dispatch input
        uses: haya14busa/action-cond@v1
        id: setPreId
        with:
          cond: ${{ github.event_name == 'workflow_dispatch' && inputs.preId != 'prerelease' }}
          if_true: ${{ inputs.preId }}
          if_false: 'prerelease'
      - run: |
          echo "${{ steps.setPreId.outputs.value }}"
          echo "${{ steps.setBumb.outputs.value }}"
    outputs:
      calculatedBumb: ${{ steps.setBumb.outputs.value }}
      calculatedPreId: ${{ steps.setPreId.outputs.value }}


  createTag:
    runs-on: ubuntu-latest
    needs:
      - env
    steps:
      - id: next_version
        uses: zwaldowski/semver-release-action@v3
        with: 
          prefix: "v"
          preid: ${{ needs.env.outputs.calculatedPreId }}        
          bump: ${{ needs.env.outputs.calculatedBumb }}
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - run: echo "${{ needs.env.steps.next_version.outputs.version }}"
