name: Release Actions-R-Us/actions-tagger@latest (Actions Tagger)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}