name: Release avakar/tag-and-release@v1

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release Tag"
        required: true
        default: "null"
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ inputs.releaseTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}