name: Release rymndhng/release-on-push-action@master
on:
  workflow_dispatch:
    inputs:
      releaseTitle:
        description: "Add to release title starting with 'Release '"
        required: true
        default: "null"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          release_name: "Release ${{ inputs.releaseTitle }}"
          bump_version_scheme: patch
          use_github_release_notes: true
          
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"