name: Release rymndhng/release-on-push-action@master (2 workflow -> publish release and build)
on:
  workflow_dispatch:
    inputs:
      releaseTitle:
        description: "Add to release title starting with 'Release '"
        required: true
        default: "null"
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        name: Release
        uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          release_name: "Release ${{ inputs.releaseTitle }}"
          bump_version_scheme: patch
          use_github_release_notes: true
        outputs:
          tagName: ${{ steps.release.outputs.tag_name }}
          version: ${{ steps.release.outputs.version }}
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    needs:
      - release
    steps:       
      - name: build and deploy test
        run: |
          echo "build and deployed ${{ needs.release.outputs.tagName }}"
          echo "release version ${{ needs.release.outputs.version }}"