name: Release rymndhng/release-on-push-action@master
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release Tag"
        required: true
        default: "null"
        type: string
      releaseVersion:
        description: "Release Version"
        required: true
        default: "null"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - id: release
          uses: poltio/action-release@v0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}