name: Release rymndhng/release-on-push-action@master
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release Tag"
        required: true
        default: "null"
        type: string
      releaseVersion:
        description: "Release Version"
        required: true
        default: "null"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          release_name: "Release ${{ inputs.releaseTag }}"
          bump_version_scheme: patch
          use_github_release_notes: true
          release_body: "When set, adds extra text to body!"
          
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"